openapi: 3.0.0
info:
  title: Money Transfer API
  description: API for managing user accounts, balances, and transactions
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /:
    get:
      summary: Health check
      description: Check if the API is running
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: string
                example: "OK"

  /user/register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '200':
          description: User created successfully
        '409':
          description: User already exists
        '500':
          description: Failed to create user

  /user/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials

  /user:
    get:
      summary: Get user information
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  balance:
                    type: number
                    format: decimal
        '401':
          description: Unauthorized
        '404':
          description: User not found

  /balance:
    get:
      summary: Get user balance
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current balance
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    format: decimal
        '401':
          description: Unauthorized
        '404':
          description: User not found

  /balance/add:
    post:
      summary: Add amount to balance
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: decimal
                  minimum: 0
              required:
                - amount
      responses:
        '200':
          description: Balance updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    format: decimal
        '400':
          description: Amount must be positive
        '401':
          description: Unauthorized
        '500':
          description: Failed to update balance

  /transactions:
    get:
      summary: Get user transactions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    transaction_type:
                      type: string
                      enum: [SENT, RECEIVED]
                    amount:
                      type: number
                      format: decimal
                    status:
                      type: string
                      enum: [SUCCESS, FAILURE]
        '401':
          description: Unauthorized
        '500':
          description: Failed to fetch transactions

  /transaction/send:
    post:
      summary: Send money to another user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: decimal
                  minimum: 0
                email:
                  type: string
                  format: email
              required:
                - amount
                - email
      responses:
        '200':
          description: Transaction successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type: number
                    format: decimal
                  receiver_email:
                    type: string
                  balance:
                    type: number
                    format: decimal
                  message:
                    type: string
        '400':
          description: Invalid amount or insufficient balance
        '401':
          description: Unauthorized
        '404':
          description: Receiver not found
        '500':
          description: Transaction failed

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT