name: Docker Compose Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build with Docker Compose
      run: docker-compose up --build -d

    - name: Check running containers
      run: docker-compose ps

    - name: Check container logs
      run: docker-compose logs

    - name: Cleanup
      run: docker-compose down